name: test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: run tests
        run: |
          cargo fmt -- --check
          cargo clippy --no-deps -- --deny warnings
          cargo test
